services:
  app:
    build: ./app
    restart: unless-stopped
    ports:
      - "5001:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - app
