services:
  app:
    image: lucas-rex.cr.de-fra.ionos.com/miranui/miranui-poc-app:latest
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - .env:/app/.env

  frontend:
    image: lucas-rex.cr.de-fra.ionos.com/miranui/miranui-poc-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - app
