name: Deploy to Ionos VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.IONOS_SSH_PRIVATE_KEY }}

    - name: Copy files to Ionos VM
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ \
        ${{ secrets.IONOS_USER }}@${{ secrets.IONOS_HOST }}:/home/${{ secrets.IONOS_USER }}/app

    - name: Remote deploy commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.IONOS_USER }}@${{ secrets.IONOS_HOST }} << 'EOF'
          cd ~/app/deploy
          bash setup.sh
        EOF
